[package]
name = "eccfs-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
eccfs = { path = "../eccfs/", features = ["std"]}
hex = "0.4.3"
libc = "0.2"
rand = "0.8.5"
rand_core = "0.6.4"

[dev-dependencies]
env_logger = "0.11.1"
log = "0.4.20"
